package com.softwareag.controlplane.agentaws.util.constants;

public class Constants {
    private Constants() {
    }

    public static final String AWS_REGION = "AWS_REGION_VALUE";

    public static final String AWS_STAGE = "AWS_STAGE";
    public static final String AWS_METRICS_BY_DATA_OR_STATISTICS = "AWS_METRICS_BY_DATA_OR_STATISTICS";
    public static final String AWS_METRICS_SYNC_BUFFER_TIME = "AWS_METRICS_SYNC_BUFFER_TIME";
    public static final String AWS_ASSETS_SYNC_BUFFER_TIME = "AWS_ASSETS_SYNC_BUFFER_TIME";
    public static final String APICP_HEARTBEAT_SEND_INTERVAL = "APICP_HEARTBEAT_SEND_INTERVAL";
    public static final String APICP_METRICS_SEND_INTERVAL = "APICP_METRICS_SEND_INTERVAL";
    public static final String APICP_ASSETS_SYNC_INTERVAL = "APICP_ASSETS_SYNC_INTERVAL";
    public static final String APICP_RUNTIME_NAME = "APICP_RUNTIME_NAME";
    public static final String APICP_RUNTIME_DESCRIPTION = "APICP_RUNTIME_DESCRIPTION";
    public static final String APICP_RUNTIME_REGION = "APICP_RUNTIME_REGION";
    public static final String APICP_RUNTIME_LOCATION = "APICP_RUNTIME_LOCATION";
    public static final String APICP_RUNTIME_TAGS = "APICP_RUNTIME_TAGS";
    public static final String APICP_RUNTIME_CAPACITY = "APICP_RUNTIME_CAPACITY";
    public static final String APICP_RUNTIME_CAPACITY_UNIT = "APICP_RUNTIME_CAPACITY_UNIT";
    public static final String APICP_RUNTIME_TYPE_ID = "APICP_RUNTIME_TYPE_ID";
    public static final String APICP_CONTROLPLANE_URL = "APICP_CONTROLPLANE_URL";
    public static final String APICP_CONTROLPLANE_USERNAME = "APICP_CONTROLPLANE_USERNAME";
    public static final String APICP_CONTROLPLANE_PASSWORD = "APICP_CONTROLPLANE_PASSWORD";
    public static final String AWS_CREDENTIALS_PROVIDER = "AWS_CREDENTIALS_PROVIDER";
    public static final String APICP_PUBLISH_ASSETS = "APICP_PUBLISH_ASSETS";
    public static final String APICP_SYNC_ASSETS = "APICP_SYNC_ASSETS";
    public static final String APICP_SEND_METRICS = "APICP_SEND_METRICS";

    public static final String APICP_CONTROLPLANE_SSL_ENABLED = "APICP_CONTROLPLANE_SSL_ENABLED";
    public static final String APICP_CONTROLPLANE_TRUST_STORE_PATH = "APICP_CONTROLPLANE_TRUST_STORE_PATH";
    public static final String APICP_CONTROLPLANE_TRUST_STORE_PASSWORD = "APICP_CONTROLPLANE_TRUST_STORE_PASSWORD";
    public static final String APICP_CONTROLPLANE_TRUST_STORE_TYPE = "APICP_CONTROLPLANE_TRUST_STORE_TYPE";
    public static final String APICP_CONTROLPLANE_KEY_STRORE_PATH = "APICP_CONTROLPLANE_KEY_STRORE_PATH";
    public static final String APICP_CONTROLPLANE_KEY_STRORE_PASSWORD = "APICP_CONTROLPLANE_KEY_STRORE_PASSWORD";
    public static final String APICP_CONTROLPLANE_KEY_STORE_TYPE = "APICP_CONTROLPLANE_KEY_STORE_TYPE";
    public static final String APICP_CONTROLPLANE_KEY_ALIAS = "APICP_CONTROLPLANE_KEY_ALIAS";
    public static final String APICP_CONTROLPLANE_KEY_PASSWORD = "APICP_CONTROLPLANE_KEY_PASSWORD";
}
